modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "GPL3"

[[mods]]
modId = "accelerateddecay"
version = "${version}"
displayName = "Accelerated Decay"
authors = "ErrorMikey"
description = '''
Speeds up the decay of leaves
'''
#logoFile = ""

[[dependencies.accelerateddecay]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.accelerateddecay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.accelerateddecay]]
modId = "architectury"
mandatory = true
versionRange = "[7.0.65,)"
ordering = "AFTER"
side = "BOTH"
