name: Build

on:
  push:
    branches: [ main, "mc/1.*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: nanite/workflows/.github/workflows/base-java.yml@v1
        with:
          use-snapshots: true
          gradle-tasks: build publish
        secrets:
          saps-token: ${{ secrets.SAPS_TOKEN }}
